DISPLAYDRIVER_VERSION = 1.0
DISPLAYDRIVER_SITE = $(TOPDIR)/package/DisplayDriver
DISPLAYDRIVER_SITE_METHOD = local
DISPLAYDRIVER_LICENSE = MIT

DISPLAYDRIVER_DEPENDENCIES = linux

define DISPLAYDRIVER_BUILD_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D)
endef

define DISPLAYDRIVER_INSTALL_TARGET_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D) modules_install
endef

$(eval $(generic-package))
